name: ncc_outfit
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  google_sign_in: ^4.5.3
  fluttertoast: ^8.0.8
  modal_progress_hud: ^0.1.3
  pinput: ^1.2.0


  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - images/
    - files/

